// Types mirroring the backend's patient and case schemas.

export type Sex = "male" | "female" | "other";

export interface Patient {
  id: string;
  mrn: string;
  first_name: string;
  last_name: string;
  sex: Sex;
  age: number;
  clinician_id: string;
}

export interface PatientCreate {
  // mrn is generated by the backend (MRN-0001 per clinician), not supplied here.
  first_name: string;
  last_name: string;
  sex: Sex;
  age: number;
}

export interface CaseSummary {
  id: string;
  patient_id: string;
  patient_mrn: string;
  patient_name: string;
  model_name: string;
  created_at: string;
}

// Full case detail: results is the stored analysis JSON (lean — no base64).
export interface CaseDetail {
  id: string;
  patient_id: string;
  clinician_id: string;
  model_name: string;
  scan_key: string | null;
  results: {
    num_present: number;
    disclaimer: string;
    findings: Array<{
      name: string;
      probability: number;
      threshold: number;
      has_heatmap: boolean;
      articles: Array<{
        pmid: string;
        title: string;
        journal: string;
        year: string;
        url: string;
      }>;
    }>;
  };
  created_at: string;
}
